install.packages("bibliometrix")
library(bibliometrix)

#For multiple bibtex files (suppose files are stored in downloads folder)
d <- list.files("~/Downloads", pattern="\\.bib$", full.names=TRUE)

i<-lapply(d,readLines)

write(unlist(i), file = "~/Downloads/JET.bib")  

# For the single file

M<-convert2df(file = "~/Downloads/JET.bib",
                     dbsource="wos",format = "bibtex")


r<-biblioAnalysis(M,sep=";")
options(width=100)
s<-summary(r,k=10)
# saving your results
a<-s[]$MostProdCountries#saving countrywide production result
write.csv(a,file="path of your outoput file and name")

#Plotting
plot(x = r, k = 20, pause = FALSE)

#Country collaboration
Mc <- metaTagExtraction(M, Field = "AU_CO", sep = ";")
NetMatrix <- biblioNetwork(Mc, analysis = "collaboration", 
                           network = "countries", sep = ";")


# Plot the country network
networkPlot(NetMatrix, n = 30,
                Title = "Country Collaboration", type = "auto",
                normalize="association",label=T,
                size=T, remove.multiple=F,remove.isolates=T,
                edgesize=4, halo=F, community.repulsion = 1,
                curved=0.2, noloops=T,
                labelsize=1)

#Key-word occurrence
Mk <- metaTagExtraction(M, Field = "ID", sep = ";")
NetkeyMatrix <- biblioNetwork(Mk, analysis = "co-occurrences", 
                           network = "keywords", sep = ";")

# Plot the network
networkPlot(NetkeyMatrix, normalize="association", 
                weighted=T, n = 50, Title = "Keyword Co-occurrences", 
                type = "fruchterman", size=T,edgesize = 0.5,labelsize=0.8,
                curved=0.2,halo=T)
#Suppose one wants to plot using the csv network file generated by the bibliometrix app that we will learn in coming sub-section.
#Country collaboration From the CSV table
WC<-read.csv(file="path to the input file",header=T)
#Removing the third column to make the edgefile
WCedge<-WC[,-c(3)]
#To generate network from the csv file, lets use igraph package
library(igraph)
#For more inclusive visual features, one can also use statnet package
library(statnet)
# Lets make the network from our csv file
g <- graph.data.frame(WCedge, directed=F)
#Storing the degrees of vertices to use them in visuals
D<-igraph::degree(g, mode="total")
h<-g%>%set_edge_attr("weight", value = WC$Frequency)%>%
  set_edge_attr("color", value =D )
#Using the tkplot for an interactive visual
tkplot(h,
       vertex.size = D*3, edge.curved=0.3,vertex.label.color="black",remove.loops=F,
       edge.width=E(g)$weight/2, #edge.arrow.size = .5,
       vertex.color = D,layout=layout.kamada.kawai#layout.fruchterman.reingold#layout.kamada.kawai
)

#Lets try run the analysis using the web-based application of bibliometrix package.
#Use the following command to open the interface in your web browser. 
biblioshiny()
#As soon as you get the app opened, it will disable the Rstudio script file and you can perform all the analysis using the application. 
Navigate the options and refer to the [Bibliometrix package docuemnt by the creaters] (https://cran.r-project.org/web/packages/bibliometrix/bibliometrix.pdf) 
